export const sampleNotes = [
  {
    id: 1,
    title: "React Hooks Part 1",
    description: "useEffect leverage the component lifecycle hooks",
    tag: { color: "blue", text: "note 1" },
    createdDate: "4th June 2021",
    dueDate: null,
    contact: "Mohan Singh",
  },
  {
    id: 2,
    title: "React Hooks Part 2",
    description: "useState makes functional components stateful",
    tag: { color: "red", text: "note 2" },
    createdDate: "5th June 2021",
    dueDate: "30th June 2021",
    contact: "Rohan Singh",
  },
  {
    id: 3,
    title: "Feedback",
    description: "Feedback V1.0",
    tag: { color: "green", text: "note 3" },
    createdDate: "6th June 2021",
    dueDate: null,
    contact: "Sohan Singh",
  },
  {
    id: 4,
    title: "Feedback hover",
    description: "Feedback V2.0",
    tag: { color: "yellow", text: "note 4" },
    createdDate: "7th June 2021",
    dueDate: "30th June 2021",
    contact: "Sandeep Kumar",
  },
];
